---
test_name: Enable primary
stages:
  - name: Enable primary
    request:
      url: "{env_vars.VAULT_ADDR}/v1/sys/replication/performance/primary/enable"
      method: PUT
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"
      json:
        primary_cluster_addr: "https://proxy.lxd:8201"
    response:
      status_code: 200
