---
test_name: 01-Create vault server certificate
stages:
  - name: 02-Create vault01 server certificate
    request:
      url: "{env_vars.VAULT_ADDR}/v1/pki/issue/lxd"
      method: POST
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"
      json:
        common_name: "{env_vars.VAULT_CLUSTER}-vault01.lxd"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            path: "{env_vars.VAULT_DATA}/ssl/{env_vars.VAULT_CLUSTER}-vault01.json"
  - name: 03-Create vault02 server certificate
    request:
      url: "{env_vars.VAULT_ADDR}/v1/pki/issue/lxd"
      method: POST
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"
      json:
        common_name: "{env_vars.VAULT_CLUSTER}.lxd"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            path: "{env_vars.VAULT_DATA}/ssl/{env_vars.VAULT_CLUSTER}-vault02.json"
  - name: 04-Create vault03 server certificate
    request:
      url: "{env_vars.VAULT_ADDR}/v1/pki/issue/lxd"
      method: POST
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"
      json:
        common_name: "{env_vars.VAULT_CLUSTER}-vault03.lxd"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            path: "{env_vars.VAULT_DATA}/ssl/{env_vars.VAULT_CLUSTER}-vault03.json"
  - name: 05-Create unsealer server certificate
    request:
      url: "{env_vars.VAULT_ADDR}/v1/pki/issue/lxd"
      method: POST
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"
      json:
        common_name: "{env_vars.VAULT_CLUSTER}-unsealer.lxd"
        ip_sans: "127.0.0.1"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            path: "{env_vars.VAULT_DATA}/ssl/{env_vars.VAULT_CLUSTER}-unsealer.json"
  - name: 06-Create Consul01 server certificate
    request:
      url: "{env_vars.VAULT_ADDR}/v1/pki/issue/lxd"
      method: POST
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"
      json:
        common_name: "{env_vars.VAULT_CLUSTER}-consul01.lxd"
        ip_sans: "127.0.0.1"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            path: "{env_vars.VAULT_DATA}/ssl/{env_vars.VAULT_CLUSTER}-consul01.json"
  - name: 07-Create Consul02 server certificate
    request:
      url: "{env_vars.VAULT_ADDR}/v1/pki/issue/lxd"
      method: POST
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"
      json:
        common_name: "{env_vars.VAULT_CLUSTER}-consul02.lxd"
        ip_sans: "127.0.0.1"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            path: "{env_vars.VAULT_DATA}/ssl/{env_vars.VAULT_CLUSTER}-consul02.json"
  - name: 08-Create Consul03 server certificate
    request:
      url: "{env_vars.VAULT_ADDR}/v1/pki/issue/lxd"
      method: POST
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"
      json:
        common_name: "{env_vars.VAULT_CLUSTER}-consul03.lxd"
        ip_sans: "127.0.0.1"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            path: "{env_vars.VAULT_DATA}/ssl/{env_vars.VAULT_CLUSTER}-consul03.json"                        