#!/bin/bash -e
####
# INFRA
###
# To enable debug: export DEBUG=true
# Enable debug if the env variable DEBUG is set to true
if [[ "$DEBUG" == "true" ]];then
    set -x
fi
#External variables
if [ "$0" == "infra/p" ]; then
    export VAULT_CLUSTER="primary"
else
    export VAULT_CLUSTER="secondary"
fi
#Internal variables
STORAGE=${STORAGE:-"raft"}
VAULT_VERSION="1.3.4"
bold=$(tput bold)
normal=$(tput sgr0)
typeset -a VAULT_primary_PORTS=("9201" "9202" "9203")
typeset -a VAULT_secondary_PORTS=("9301" "9302" "9303")
typeset -a VAULT_dr_PORTS=("9401" "9402" "9403")

echo "# Using storage: ${STORAGE}"
case "$1" in
     help)
        echo "${bold}Usage: $0 <command> <subcommand>${normal}"
        echo ""
        echo "${bold}sh${normal}: <container name>"
        echo "${bold}status${normal}: <systemd service>"
        echo "${bold}exec_all${normal}: <command>"
        echo "${bold}exec${normal}: <container name> <command>"
        echo "${bold}logs${normal}: <systemd service>"
        echo "${bold}restart_vault${normal}"
        echo "${bold}restart_consul${normal}"
    ;;     
    "sh")
        lxc exec ${VAULT_CLUSTER}-$2 bash
    ;;
    "status")
            set +e
        for i in "vault01" "vault02" "vault03" "unsealer" "pki"; do
            echo "${VAULT_CLUSTER}-${i}:"
            lxc exec ${VAULT_CLUSTER}-${i} --  systemctl -o short --no-pager --lines 0 status $2
        done
        if [ "${STORAGE}" == "consul" ]; then
            for i in "consul01" "consul02" "consul03"; do
                lxc exec ${VAULT_CLUSTER}-${i} -- systemctl -o short --no-pager --lines 0 status $2
            done
        fi    
    ;;
    "exec_all")
        for i in "vault01" "vault02" "vault03" "unsealer" "pki"; do
            lxc exec ${VAULT_CLUSTER}-${i} -- ${@:2}
        done
        if [ "${STORAGE}" == "consul" ]; then
            for i in "consul01" "consul02" "consul03"; do
                lxc exec ${VAULT_CLUSTER}-${i} -- ${@:2}
            done
        fi
    ;;
    "exec")
        lxc exec ${VAULT_CLUSTER}-$2 -- ${@:3}
    ;;     
    "logs")
            lxc exec ${VAULT_CLUSTER}-$2 -- journalctl --no-pager -b -f -u $3 
    ;;
    "restart_vault")

            for i in "vault01" "vault02" "vault03"; do
                    lxc exec ${VAULT_CLUSTER}-$i -- systemctl restart vault
            done
    ;;
    "restart_consul")

            for i in "consul01" "consul03" "consul02"; do
                    lxc exec ${VAULT_CLUSTER}-$i -- systemctl restart consul
            done
    ;;    
    "wipe")
        if [ ! -z "$2" ]; then
             sudo rm -fr infra/docker/storage/raft/${VAULT_CLUSTER}/$2
             mkdir -p infra/docker/storage/raft/${VAULT_CLUSTER}/$2
        else
             sudo rm -fr infra/docker/storage/raft/${VAULT_CLUSTER}
            mkdir -p infra/docker/storage/raft/${VAULT_CLUSTER}/{01,02,03,unsealer,pki}
        fi
    ;;
    "wipe_nodes")
        sudo rm -fr infra/docker/storage/raft/${VAULT_CLUSTER}/{01,02,03}
        mkdir -p infra/docker/storage/raft/${VAULT_CLUSTER}/{01,02,03}
    ;;
esac