---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  vars:
    CLUSTER_IP: "{{ cluster_ip }}"
    HOSTNAME: "{{ hostname }}"
    JOIN_RETRY: "{{ join_retry }}"
    CLUSTER: "{{ cluster_name }}"
    BIN_DIR: "/home/bruj0/backup/enterprise_bins"
  roles:
    - consul-agent
    - vault
  