---
- hosts: vault
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  vars:
    CONSUL: false
    RAFT: true
    CLUSTER_IP: "{{ cluster_ip }}"
    HOSTNAME: "{{ hostname }}"
    JOIN_RETRY: "{{ join_retry }}"
    CLUSTER: "{{ cluster_name }}"
    BIN_DIR: "/home/bruj0/backup/data/enterprise_bins"
    vault_template_name: "{{ 'vault-pki.hcl.j2' if 'pki' in HOSTNAME else 'vault-unsealer.hcl.j2' if 'unsealer' in HOSTNAME else 'vault.hcl.j2' }}"
  roles:
    - consul-agent
    - vault
- hosts: consul
  become: yes
  become_user: root
  become_method: sudo
  vars:
    CLUSTER_IP: "{{ cluster_ip }}"
    HOSTNAME: "{{ hostname }}"
    JOIN_RETRY: "{{ join_retry }}"
    CLUSTER: "{{ cluster_name }}"
    BIN_DIR: "/home/bruj0/backup/data/enterprise_bins"
  roles:
    - consul
