- name: Creating vault user group
  group: 
    name: "{{ vault_group }}"
  become: true

- name: Creating vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault nologin User"
    createhome: "no"
    state: present

- name: Install prerequisites
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ vault_install_prerequisites }}"
  become: yes

- name: "Unzip vault archive"
  unarchive:
    src: "{{ BIN_DIR }}/vault/{{ vault_version }}/vault-enterprise_{{ vault_version }}+prem_linux_amd64.zip"
    dest: /usr/local/bin
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755

- name: "Set vault binary capabilities"
  capabilities:
    path: /usr/local/bin/vault
    capability: cap_ipc_lock+ep
    state: present

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
  notify: systemd_reload

- name: Ensures {{vault_config_path}} dir exists
  file: path={{vault_config_path}} state=directory

- name: Ensures /var/raft dir exists
  file: path="/var/raft" state=directory

- name: config file
  template:
    src: "{{ vault_template_name }}"
    dest: "{{ vault_config_path }}/vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: vault service
  service:
    name: vault
    state: stopped
    enabled: yes
