- name: Creating consul user group
  group: 
    name: "{{ consul_group }}"
  become: true

- name: Creating consul user
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "consul nologin User"
    createhome: "no"
    state: present

- name: Install prerequisites
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ consul_install_prerequisites }}"
  become: yes

- name: Check if Consul binary exists
  stat:
    path: /usr/local/bin/consul
  register: stat_result

- name: "Unzip consul archive"
  unarchive:
    src: "{{ BIN_DIR }}/consul/{{consul_version}}/consul-enterprise_{{consul_version}}+prem_linux_amd64.zip"
    dest: /usr/local/bin
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
  when: not stat_result.stat.exists
  
- name: Copy systemd init file
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
  notify: systemd_reload

- name: Ensures {{consul_config_path}} dir exists
  file: path={{consul_config_path}} state=directory
  
- name: client config file
  template:
    src: client_agent.json.j2
    dest: "{{ consul_config_path }}/client_agent.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"

- name: consul service
  service:
    name: consul
    state: stopped
    enabled: yes
